packages:
  - name: joplin-bin
    check_type: github
    upstream: laurent22/joplin
    tag_pattern: 's/^v//'
  - name: freetube-bin
    check_type: github
    upstream: FreeTubeApp/FreeTube
    tag_pattern: 's/^v//;s/-beta$//'
    release_type: any
  - name: ttf-ezhuthu
    check_type: gitlab
    upstream: rit-fonts/ezhuthu
    tag_pattern: 's/^v//'
