packages:
  - name: joplin-bin
    check_type: github
    upstream: laurent22/joplin
    tag_pattern: 's/^v//'
  - name: freetube-bin
    check_type: github
    upstream: FreeTubeApp/FreeTube
    tag_pattern: 's/^v//;s/-beta$//'
    release_type: any
  - name: ttf-ezhuthu
    check_type: gitlab
    upstream: rit-fonts/ezhuthu
    tag_pattern: 's/^v//'
  - name: xmind
    check_type: xmind_custom
    url: https://xmind.app/zen/download/linux_deb/
    filename_prefix: Xmind-for-Linux-amd64bit-
    pkgver_var: _pkgver
  - name: liberica-jdk-11-bin
    check_type: liberica
    upstream: bell-sw/Liberica
    tag_prefix: "11."
  - name: liberica-jdk-11-full-bin
    check_type: liberica
    upstream: bell-sw/Liberica
    tag_prefix: "11."
    variant: full
  - name: liberica-jdk-11-lite-bin
    check_type: liberica
    upstream: bell-sw/Liberica
    tag_prefix: "11."
    variant: lite
  - name: liberica-jdk-17-full-bin
    check_type: liberica
    upstream: bell-sw/Liberica
    tag_prefix: "17."
    variant: full
